?  const translations = {
    es: {
      pageTitle: 'Quetzal Systems — Sitios web para negocios de Costa Rica', brand: 'Quetzal Systems', brandLabel: 'Quetzal Systems',
      navService: 'Servicio', navProjects: 'Proyectos', navProcess: 'Cómo funciona', navContact: 'Escribime',
      accessibilityTitle: 'Accesibilidad', accessibilityToolsLabel: 'Herramientas de accesibilidad', accessibilityToggleLabel: 'Abrir opciones de accesibilidad', accessibilityCloseLabel: 'Cerrar opciones de accesibilidad',
      languageLabel: 'Idioma', languageButton: 'EN', languageGroupLabel: 'Selección de idioma',
      themeLabel: 'Tema', themeButton: 'Claro', themeGroupLabel: 'Selección de tema',
      textSizeLabel: 'Tamaño del texto', textSizeGroupLabel: 'Selección de tamaño de texto',
      heroTitle: 'Tu negocio ya existe. Hagamos Que también lo encuentren en internet.',
      eyebrow: 'Desarrollo web · Costa Rica', heroLead: 'Diseño y desarrollo sitios web y tiendas en línea para pymes, turismo rural y negocios costarricenses — hechos a la medida, no con plantillas genéricas.',
      heroPrimary: 'Hablemos de tu proyecto', heroSecondary: 'Ver proyectos realizados', terminalSearchLabel: 'buscar:', terminalSearch: '"tours cerca de mí" / "joyería artesanal CR"', terminalResult: 'tu negocio aparece', terminalBooking: 'el cliente reserva o compra sin llamarte', terminalStatusLabel: 'estado:', terminalStatus: 'en línea',
      problemLabel: 'El problema', problemTitle: 'La gente te busca antes de conocerte',
      problemTextOne: 'Alguien que quiere visitar una cascada, comprar una joya artesanal o encontrar un negocio local casi siempre empieza en Google o Instagram. Si no aparecés ahí, con información clara y una forma fácil de contactarte o comprarte, <strong>ese cliente termina en el negocio de al lado</strong> — no porque sea mejor, sino porque fue el que sí encontró.',
      problemTextTwo: 'Un sitio web bien hecho no es un gasto de imagen. Es la diferencia entre que un turista reserve tu tour directamente o que un artesano venda sus piezas fuera de la feria del fin de semana. <strong>Es infraestructura para vender más</strong>, todos los días, sin que vos tengas que estar detrás de cada mensaje.',
      serviceLabel: 'El servicio', serviceTitle: 'Un sitio web hecho para tu negocio, no un molde reciclado', serviceName: 'Sitio web a la medida',
      serviceDescription: 'Diseño y desarrollo completo: desde la primera conversación sobre tu negocio hasta el sitio publicado y funcionando. Incluye lo que tu negocio realmente necesita, sin relleno.', serviceAudience: 'Ideal para turismo rural, tiendas artesanales, servicios locales y pymes que quieren verse tan serias en línea como lo son en persona.', priceFrom: 'Precios accesibles', priceUnit: '/ proyecto', priceNote: 'Nos ajustamos en la primera conversación.',
      featureDesign: '<b>Diseño a la medida</b> — nada de plantillas genéricas', featureBilingual: '<b>Bilingüe (ES/EN)</b> si tu negocio recibe turismo extranjero', featureStore: '<b>Tienda en línea</b> con catálogo y pedidos, si vendés productos', featureMobile: '<b>Optimizado para celular</b> — así es como te va a buscar la mayoría', featureSupport: '<b>Acompañamiento post-entrega</b> para ajustes y dudas',
      casesLabel: 'Proyectos reales', casesTitle: 'Trabajos realizados', caseLinkLabel: 'Visitar sitio web de Joyería Creativas', caseVisual: 'Joyería Creativas', galleryLabel: 'Galería de productos de Joyería Creativas', galleryPhotoOne: 'Productos', galleryPhotoTwo: 'Aretes', galleryPhotoThree: 'Anillos', galleryPhotoFour: 'Joyería artesanal', caseTag: 'E-COMMERCE ARTESANAL', caseTitle: 'Joyería Creativas', caseDescription: 'Sitio web para una marca de joyería creativa, con una presentación clara de sus productos y una experiencia digital pensada para sus clientes.', caseVisit: 'Visitar sitio web',
      processLabel: 'Cómo funciona', processTitle: 'De la idea al sitio publicado', stepOneTitle: 'Conversamos', stepOneText: 'Me contás sobre tu negocio, quiénes son tus clientes y qué necesitás que el sitio haga por vos.', stepTwoTitle: 'Diseño y desarrollo', stepTwoText: 'Construyo el sitio a la medida de tu negocio, con revisiones en el camino para que vaya como lo imaginás.', stepThreeTitle: 'Ajustes finales', stepThreeText: 'Revisamos juntos, afinamos textos, imágenes y detalles hasta que quede listo para publicarse.', stepFourTitle: 'Publicación', stepFourText: 'Tu sitio queda en línea y funcionando, con acompañamiento si surge algo después.',
      contactTitle: '¿Listo para que te encuentren en internet?', contactText: 'Contame de tu negocio y hablamos sin compromiso sobre qué necesita tu sitio web.', contactWhatsapp: 'Escribir por WhatsApp', contactEmail: 'Enviar un correo', contactWhatsappLabel: 'WhatsApp:', contactEmailLabel: 'Correo:', footerBrand: 'Quetzal Systems — Desarrollo web, Costa Rica', footerCopyright: '© 2026'
    },
    en: {
      pageTitle: 'Quetzal Systems — Websites for Costa Rican businesses', brand: 'Quetzal Systems', brandLabel: 'Quetzal Systems',
      navService: 'Services', navProjects: 'Projects', navProcess: 'How it works', navContact: 'Contact me',
      accessibilityTitle: 'Accessibility', accessibilityToolsLabel: 'Accessibility tools', accessibilityToggleLabel: 'Open accessibility options', accessibilityCloseLabel: 'Close accessibility options',
      languageLabel: 'Language', languageButton: 'ES', languageGroupLabel: 'Language selection',
      themeLabel: 'Theme', themeButton: 'Dark', themeGroupLabel: 'Theme selection',
      textSizeLabel: 'Text size', textSizeGroupLabel: 'Text size selection',
      heroTitle: 'Your business exists. Let people find it online too.', eyebrow: 'Web development · Costa Rica', heroLead: 'I design and build websites and online stores for small businesses, rural tourism and Costa Rican businesses — custom-made, never generic templates.', heroPrimary: 'Let’s talk about your project', heroSecondary: 'See completed projects', terminalSearchLabel: 'search:', terminalSearch: '"tours near me" / "artisan jewelry CR"', terminalResult: 'your business appears', terminalBooking: 'customers book or buy without calling', terminalStatusLabel: 'status:', terminalStatus: 'online',
      problemLabel: 'The problem', problemTitle: 'People search for you before they know you', problemTextOne: 'Someone who wants to visit a waterfall, buy an artisan jewel or find a local business almost always starts on Google or Instagram. If you are not there with clear information and an easy way to contact or buy from you, <strong>that customer ends up at the business next door</strong> — not because it is better, but because it was the one they found.', problemTextTwo: 'A well-built website is not an image expense. It is the difference between a tourist booking your tour directly or an artisan selling pieces beyond the weekend fair. <strong>It is infrastructure for selling more</strong>, every day, without chasing every message.',
      serviceLabel: 'The service', serviceTitle: 'A website made for your business, not a recycled mold', serviceName: 'Custom website', serviceDescription: 'Complete design and development: from the first conversation about your business to a published, working site. It includes what your business truly needs, without filler.', serviceAudience: 'Ideal for rural tourism, artisan shops, local services and small businesses that want to look as professional online as they are in person.', priceFrom: 'Affordable pricing', priceUnit: '/ project', priceNote: 'We will tailor it during our first conversation.', featureDesign: '<b>Custom design</b> — no generic templates', featureBilingual: '<b>Bilingual (ES/EN)</b> if your business welcomes international visitors', featureStore: '<b>Online store</b> with catalog and orders, if you sell products', featureMobile: '<b>Mobile optimized</b> — that is how most people will find you', featureSupport: '<b>Post-launch support</b> for questions and adjustments',
      casesLabel: 'Completed projects', casesTitle: 'Completed work', caseLinkLabel: 'Visit Joyería Creativas website', caseVisual: 'Joyería Creativas', galleryLabel: 'Joyería Creativas product gallery', galleryPhotoOne: 'Products', galleryPhotoTwo: 'Earrings', galleryPhotoThree: 'Rings', galleryPhotoFour: 'Artisan jewelry', caseTag: 'ARTISAN E-COMMERCE', caseTitle: 'Joyería Creativas', caseDescription: 'Website for a creative jewelry brand, with a clear presentation of its products and a digital experience designed for its customers.', caseVisit: 'Visit website',
      processLabel: 'How it works', processTitle: 'From idea to published site', stepOneTitle: 'We talk', stepOneText: 'You tell me about your business, your customers and what you need the website to do for you.', stepTwoTitle: 'Design and development', stepTwoText: 'I build a custom site for your business, with reviews along the way so it matches your vision.', stepThreeTitle: 'Final adjustments', stepThreeText: 'We review it together and refine the copy, images and details until it is ready to launch.', stepFourTitle: 'Launch', stepFourText: 'Your site goes live and keeps working, with support if something comes up later.',
      contactTitle: 'Ready to be found online?', contactText: 'Tell me about your business and let’s discuss what your website needs, with no pressure.', contactWhatsapp: 'Message on WhatsApp', contactEmail: 'Send an email', contactWhatsappLabel: 'WhatsApp:', contactEmailLabel: 'Email:', footerBrand: 'Quetzal Systems — Web development, Costa Rica', footerCopyright: '© 2026'
    }
  };

